# Generated by Django 5.0.4 on 2024-06-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_is_null',
            field=models.BooleanField(default=False),
        ),
    ]
