# Generated by Django 5.0.4 on 2024-04-22 04:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_content', models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True)),
                ('speaker_delivery', models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True)),
                ('presentation_duration', models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True)),
                ('audio_video_quality', models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True)),
                ('how_did_you_hear', models.CharField(choices=[('E', 'Email'), ('S', 'Social Media Post'), ('W', 'WhatsApp'), ('F', 'FCPI Website'), ('R', 'Referral'), ('I', 'IDCongress2023'), ('O', 'Other')], max_length=1, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
