# Generated by Django 5.0.4 on 2024-05-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username'),
        ('accounts', '0002_rename_event_feedback_single_event'),
    ]

    operations = [
    ]
