# Generated by Django 5.0.4 on 2024-04-20 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='verisatisfied',
        ),
        migrations.AddField(
            model_name='feedback',
            name='audio_video_quality',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='how_did_you_hear',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='presentation_content',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='presentation_duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='speaker_delivery',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
