# Generated by Django 5.0.3 on 2024-03-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userrole',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
