# Generated by Django 5.0.4 on 2024-04-22 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_feedback_audio_video_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='audio_video_quality',
            field=models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='presentation_content',
            field=models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='presentation_duration',
            field=models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='speaker_delivery',
            field=models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True),
        ),
    ]
