# Generated by Django 5.0.4 on 2024-05-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_username'),
        ('admins', '0003_alter_singleevent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('single_event', 'created_at')},
        ),
    ]
