# Generated by Django 5.0.4 on 2024-05-16 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_feedback_user'),
        ('admins', '0009_remove_certificates_forum_certificates_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_event', to='admins.event'),
        ),
    ]
