# Generated by Django 5.0.4 on 2024-04-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_feedback_audio_video_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='how_did_you_hear',
            field=models.CharField(choices=[('VS', 'Email'), ('SS', 'SocialMediaPost'), ('P', ' WhatsApp'), ('VO', 'FCPIWebsite'), ('VV', 'Referral'), ('VH', ' IDCongress2023'), ('VN', ' Other')], max_length=100, null=True),
        ),
    ]
