# Generated by Django 5.0.4 on 2024-08-30 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_phone'),
        ('admins', '0032_alter_generalmultievent_single_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEnrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_event_enrollments', to='admins.generalevent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_userevent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
