# Generated by Django 5.0.4 on 2024-05-16 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_feedback_user'),
        ('admins', '0009_remove_certificates_forum_certificates_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='admins.event'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to=settings.AUTH_USER_MODEL),
        ),
    ]
