# Generated by Django 5.0.4 on 2024-05-22 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_feedback_unique_together'),
        ('admins', '0004_alter_singleevent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='single_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackss', to='admins.certificates'),
        ),
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('single_event', 'created_at')},
        ),
    ]
