# Generated by Django 5.0.4 on 2024-08-31 05:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_generalenrolled'),
        ('admins', '0032_alter_generalmultievent_single_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_content', models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True)),
                ('speaker_delivery', models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True)),
                ('presentation_duration', models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True)),
                ('audio_video_quality', models.CharField(choices=[('VS', 'Very Satisfied'), ('SS', 'Somewhat Satisfied'), ('N', 'Neutral'), ('US', 'Unsatisfied'), ('VU', 'Very Unsatisfied')], max_length=2, null=True)),
                ('how_did_you_hear', models.CharField(choices=[('E', 'Email'), ('S', 'Social Media Post'), ('W', 'WhatsApp'), ('F', 'FCPI Website'), ('R', 'Referral'), ('I', 'IDCongress2023'), ('O', 'Other')], max_length=1, null=True)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('single_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_feedbacks', to='admins.generalsingleevent')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('single_event', 'created_at')},
            },
        ),
    ]
