# Generated by Django 5.0.4 on 2024-05-17 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_feedback_event_alter_feedback_user'),
        ('admins', '0011_remove_certificates_feedback_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='admins.event'),
        ),
    ]
