# Generated by Django 5.0.4 on 2024-05-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_feedback_single_event_and_more'),
        ('admins', '0004_alter_singleevent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='certificates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackss', to='admins.certificates'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='single_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='admins.singleevent'),
        ),
    ]
