# Generated by Django 5.0.4 on 2024-05-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_feedback_certificates_alter_feedback_single_event'),
        ('admins', '0004_alter_singleevent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='certificates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacksss', to='admins.certificates'),
        ),
    ]
