# Generated by Django 5.0.4 on 2024-05-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_feedback_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='certificates',
        ),
    ]
