# Generated by Django 5.0.4 on 2024-05-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='selected_day',
            field=models.IntegerField(null=True),
        ),
    ]
