# Generated by Django 5.0.4 on 2024-05-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_feedback_selected_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='selected_day',
        ),
    ]
