# Generated by Django 5.0.4 on 2024-06-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_enrolled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_work_institution',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
