# Generated by Django 5.0.4 on 2024-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_feedback_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
