# Generated by Django 5.0.4 on 2024-05-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_feedback_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='day',
        ),
    ]
