# Generated by Django 5.0.4 on 2024-04-20 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0040_singleevent_date_singleevent_day'),
        ('speaker', '0004_alter_message_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_messages', to='admins.event'),
        ),
        migrations.AddField(
            model_name='message',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='admins.forum'),
        ),
    ]
