# Generated by Django 5.0.4 on 2024-04-23 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0005_message_event_message_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='forum',
        ),
    ]
