# Generated by Django 5.0.4 on 2024-04-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0040_singleevent_date_singleevent_day'),
        ('speaker', '0006_remove_message_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='admins.forum'),
        ),
    ]
