# Generated by Django 5.0.4 on 2024-04-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0007_message_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
