from django.contrib import admin
from django.urls import path, include
from .views import *

urlpatterns = [
    path('register/', RegisterView.as_view()),
    path('verifyOtp/', VerifyOtp.as_view(), name='verify_otp'),
    path('resendOtp/', ResendOtp.as_view(), name='resend-otp'),
    # path('login/', LoginView.as_view(), name='login'),
    path('token/', MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('add_user/', AddUser.as_view(), name='add_user'),
    path('user-roles/', UserRoleListView.as_view(), name='user_roles_list'),
    path('create-roles/', UserRoleCreateView.as_view(), name='create_roles_create'),
    path('userlist/', UserListView.as_view(), name='user-list'),
    path('useralllist/', UserAllListView.as_view(), name='user-list'),
    path('userprofile/', UserProfileCreateView.as_view(), name='user_profile'),
    path('userprofilelist/',  UserprofileListView.as_view(), name='user_profile_list'),
    path('user/<int:pk>/update/', updateUser.as_view(), name='user-update'),
    path('user/<int:pk>/delete/', DeleteUser.as_view(), name='user-delete'),
    path('singleuser/', UserProfileView.as_view(), name='user-profile'),
    path('feedback/', FeedbackCreateView.as_view(), name='feedback-create'), 
    path('general_feedback/', GeneralFeedbackCreateView.as_view(), name='feedback-create'),
    path('ecertificate/', CertificateView.as_view(), name='certificate-view'),
    path('usercertificate/', AuthenticatedUserView.as_view(), name='authenticated-user'),
    path('user/<int:user_id>/', UserProfileAPIView.as_view(), name='user_profile_api'),
    path('enroll/<slug:slug>/', EnrollEvent.as_view(), name='enroll_event'),
    path('general_enroll/<slug:slug>/', GeneralEnrollEvent.as_view(), name='enroll_event'),
    path('check-enrollment/<slug:slug>/', CheckEnrollmentView.as_view(), name='check_enrollment'),
    path('users/enrolled-events/', UserEnrolledEventListView.as_view(), name='user_enrolled_events'),
    path('change-password/', ChangePasswordAPIView.as_view(), name='change_password'),
    path('event-points/', EventPointsAPIView.as_view(), name='event_points'),
    path('singleuser/<int:user_id>/', UserDetailView.as_view(), name='user-detail'),
    path('user/userprofile/<int:user_id>/',UserProfileUpdateView.as_view(), name='user-profile-update'),
    path('user-delete/<int:user_id>/', UserDeleteView.as_view(), name='user-delete'),
    path('user-status/<int:user_id>/', UpdateUserStatusView.as_view(), name='update-user-status'),
    path('save-csv-data/', SaveCsvDataView.as_view(), name='save_csv_data'),
    path('forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('verify-forgot-password-otp/', VerifyForgotPasswordOtpView.as_view(), name='forgot-password'),
    path('reset-password/', ResetPasswordView.as_view(), name='reset-password'),
    path('contact/', ContactMessageAPIView.as_view(), name='contact-message'),
    path('events/<slug:slug>/enrollment-count/', EnrolledUserCountView.as_view(), name='event-enrollment-count'),
    path('usersall/', UserALLListView.as_view(), name='user-list'),
    path('user-countweek/', UserCountView.as_view(), name='user-count'),
    path('validate-email/', ValidateEmailView.as_view(), name='validate_email'),
    path('general_check-enrollment/<slug:slug>/', GeneralCheckEnrollmentView.as_view(), name='check_enrollment'),
    path('general_events/<slug:slug>/enrollment-count/', GeneralEnrolledUserCountView.as_view(), name='event-enrollment-count'),
    path('general_users/enrolled-events/', GeneralUserEnrolledEventListView.as_view(), name='user_enrolled_events'),
    path('general_ecertificate/', GeneralCertificateView.as_view(), name='certificate-view'),
    path('general_event-points/', GeneralEventPointsAPIView.as_view(), name='event_points'),
    path('users/general_enrolled-events/', GeneralUserEnrolledEventListView.as_view(), name='user_enrolled_events'),
    path('user-count/',  UserCountAPIView.as_view(), name='speaker-count-api'),
    path('monthly-user-count/', Last10MonthsUserCountAPIView.as_view(), name='monthly-user-count'),   
    path('last-10-days-user-count/', Last10DaysUserCountAPIView.as_view(), name='last_10_days_user_count'),
    path('events/<slug:slug>/enrolled-users/', EnrolledUserView.as_view(), name='enrolled_user_list'),
    # path('feedbacks/<int:single_event_id>/', EventFeedbackListView.as_view(), name='feedback-list'),
    # path('general-events/<slug:slug>/enrolled-users/', GeneralEnrolledUserView.as_view(), name='general_enrolled_user_list'),
]