# Generated by Django 5.0.4 on 2024-05-06 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_blogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='topic',
        ),
        migrations.CreateModel(
            name='BlogsContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='admins.blogs')),
            ],
        ),
    ]
