# Generated by Django 5.0.4 on 2024-05-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='singleevent',
            unique_together={('event', 'day')},
        ),
    ]
