# Generated by Django 5.0.4 on 2024-05-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('recent_job_title', models.CharField(max_length=100)),
                ('additional_job_titles', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('previous_work_experience', models.TextField()),
                ('publications', models.TextField()),
                ('current_research', models.TextField()),
                ('conference', models.TextField()),
                ('additional_information', models.TextField()),
                ('achievements', models.TextField()),
                ('areas', models.TextField()),
            ],
        ),
    ]
