# Generated by Django 5.0.4 on 2024-09-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastfcpi',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='podcastfcpi_banners/'),
        ),
    ]
