# Generated by Django 5.0.4 on 2024-05-07 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_contents',
        ),
        migrations.AddField(
            model_name='blogscontents',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='admins.blogs'),
        ),
    ]
