# Generated by Django 5.0.4 on 2024-09-11 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podcastfcpipodcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='podcastfcpipodcast_banners/')),
                ('date', models.DateField()),
                ('starting_time', models.TimeField()),
                ('ending_time', models.TimeField()),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('guests', models.ManyToManyField(related_name='podcastfcpipodcast_as_guest', to='admins.speaker')),
                ('hosts', models.ManyToManyField(related_name='podcastfcpipodcast_as_host', to='admins.speaker')),
            ],
        ),
    ]
