# Generated by Django 5.0.3 on 2024-03-14 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='topic',
            new_name='name',
        ),
    ]
