# Generated by Django 5.0.4 on 2024-07-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
