# Generated by Django 5.0.4 on 2024-09-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_podcastfcpi_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastfcpi',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='podcastfcpi',
            name='host',
        ),
        migrations.AddField(
            model_name='podcastfcpi',
            name='guests',
            field=models.ManyToManyField(related_name='podcastfcpi_as_guest', to='admins.speaker'),
        ),
        migrations.AddField(
            model_name='podcastfcpi',
            name='hosts',
            field=models.ManyToManyField(related_name='podcastfcpi_as_host', to='admins.speaker'),
        ),
    ]
