# Generated by Django 5.0.4 on 2024-09-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_podcastfcpipodcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastfcpipodcast',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='podcastfcpipodcast_images/'),
        ),
    ]
