# Generated by Django 5.0.4 on 2024-05-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_remove_blogs_blog_contents_blogscontents_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogscontents',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
