# Generated by Django 5.0.4 on 2024-05-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='achievements',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='additional_information',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='additional_job_titles',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='areas',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='conference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='current_research',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='previous_work_experience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='publications',
            field=models.CharField(max_length=100),
        ),
    ]
