# Generated by Django 5.0.4 on 2024-05-22 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_singleevent_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='singleevent',
            unique_together={('event', 'date')},
        ),
    ]
