# Generated by Django 5.0.3 on 2024-03-13 07:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title'),
        ),
    ]
