# Generated by Django 5.0.4 on 2024-09-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_podcast_hostcontents_guestcontents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostcontents',
            name='podcast',
        ),
        migrations.DeleteModel(
            name='GuestContents',
        ),
        migrations.DeleteModel(
            name='HostContents',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
    ]
