# Generated by Django 5.0.4 on 2024-05-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_blogscontents_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_contents',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='admins.blogscontents'),
        ),
    ]
