# Generated by Django 5.0.4 on 2024-05-03 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_member_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='forum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='admins.forum'),
        ),
    ]
