# Generated by Django 5.0.4 on 2024-07-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_event_event_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multievent',
            name='ending_time',
            field=models.TimeField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='multievent',
            name='starting_time',
            field=models.TimeField(blank=True, max_length=8, null=True),
        ),
    ]
