# Generated by Django 5.0.3 on 2024-03-14 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0003_alter_event_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='topic',
        ),
    ]
