# Generated by Django 5.0.4 on 2024-05-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_singleevent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
