# Generated by Django 5.0.4 on 2024-05-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_blogs_blog_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='blog_contents',
        ),
    ]
