# Generated by Django 5.0.3 on 2024-03-15 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_rename_name_event_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='events', to='admins.speaker'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_schedules', to='admins.speaker'),
        ),
    ]
