# Generated by Django 5.0.4 on 2024-05-04 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_member_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='forum',
        ),
        migrations.CreateModel(
            name='ForumMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum', to='admins.forum')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='admins.member')),
            ],
        ),
    ]
