# Generated by Django 5.0.4 on 2024-07-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0004_alter_multievent_ending_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='designation',
            field=models.CharField(max_length=1000),
        ),
    ]
