# Generated by Django 5.0.3 on 2024-03-15 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_event_speakers_alter_schedule_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to='forum_logos/'),
        ),
    ]
