# Generated by Django 5.0.4 on 2024-05-10 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_remove_blogs_blog_contents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogscontents',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='admins.blogs'),
        ),
    ]
