# Generated by Django 5.0.4 on 2024-07-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_alter_speaker_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='designation',
            field=models.TextField(),
        ),
    ]
