# Generated by Django 5.0.4 on 2024-05-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_remove_member_forum_forummember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forummember',
            name='member',
        ),
        migrations.AddField(
            model_name='forummember',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='member', to='admins.member'),
        ),
    ]
