# Generated by Django 5.0.4 on 2024-05-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_certificates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
