# Generated by Django 5.0.3 on 2024-03-15 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_forum_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='Logo',
            new_name='logo',
        ),
    ]
