# Generated by Django 5.0.4 on 2024-05-10 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_blogscontents_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogscontents',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_contents', to='admins.blogs'),
        ),
    ]
