# Generated by Django 5.0.4 on 2024-07-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_speaker_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogscontents',
            name='topic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
