# Generated by Django 5.0.4 on 2024-05-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0006_alter_certificates_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='date',
        ),
    ]
