# Generated by Django 5.0.3 on 2024-03-15 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_rename_logo_forum_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='logo',
        ),
    ]
