# Generated by Django 5.0.4 on 2024-05-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0007_remove_certificates_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
