# Generated by Django 5.0.4 on 2024-05-14 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0008_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificates',
            name='forum',
        ),
        migrations.AddField(
            model_name='certificates',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='admins.event'),
        ),
    ]
