# Generated by Django 5.0.4 on 2024-05-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author_profile',
            field=models.ImageField(blank=True, null=True, upload_to='author_profile/'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='blog_banner',
            field=models.ImageField(blank=True, null=True, upload_to='blogs_banner/'),
        ),
    ]
