# Generated by Django 5.0.4 on 2024-05-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0009_remove_certificates_forum_certificates_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='feedback_completed',
            field=models.BooleanField(default=False),
        ),
    ]
