# Generated by Django 5.0.4 on 2024-05-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0010_blogs_author_profile_blogs_blog_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ManyToManyField(blank=True, related_name='board_members', to='admins.member')),
            ],
        ),
    ]
