# Generated by Django 5.0.3 on 2024-03-21 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_remove_event_speaker_event_speakers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='single_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_events', to='admins.speaker'),
        ),
    ]
