# Generated by Django 5.0.4 on 2024-08-03 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0011_attachment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='user',
        ),
    ]
