# Generated by Django 5.0.4 on 2024-05-29 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_board'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmember',
            old_name='members',
            new_name='member',
        ),
        migrations.AddField(
            model_name='boardmember',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='board', to='admins.board'),
        ),
    ]
