# Generated by Django 5.0.3 on 2024-03-21 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_alter_event_single_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='speakers',
        ),
    ]
