# Generated by Django 5.0.4 on 2024-08-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0013_savedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedFile',
        ),
    ]
