# Generated by Django 5.0.3 on 2024-03-21 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_event_speakers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='single_speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_events', to='admins.speaker'),
        ),
    ]
