# Generated by Django 5.0.4 on 2024-05-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_member_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
