# Generated by Django 5.0.4 on 2024-08-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0015_userfileassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogscontents',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
