# Generated by Django 5.0.4 on 2024-08-09 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_blogscontents_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogscontents',
            name='image_url',
        ),
    ]
