# Generated by Django 5.0.4 on 2024-05-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0016_forum_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
