# Generated by Django 5.0.3 on 2024-03-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_remove_event_ending_time_remove_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ending_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='starting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='topics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
