# Generated by Django 5.0.4 on 2024-06-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_blogs_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
