# Generated by Django 5.0.4 on 2024-08-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0017_remove_blogscontents_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='current_research',
        ),
    ]
