# Generated by Django 5.0.3 on 2024-03-21 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_event_ending_time_event_points_event_starting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='single_speaker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_events', to='admins.speaker'),
        ),
    ]
