# Generated by Django 5.0.4 on 2024-06-01 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
