# Generated by Django 5.0.4 on 2024-08-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0018_remove_member_current_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
