# Generated by Django 5.0.3 on 2024-03-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_event_single_speaker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
