# Generated by Django 5.0.4 on 2024-08-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0019_member_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
