# Generated by Django 5.0.3 on 2024-03-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0020_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfDays', models.IntegerField()),
            ],
        ),
    ]
