# Generated by Django 5.0.4 on 2024-08-20 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0020_gallery_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralBlogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('author', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('blog_banner', models.ImageField(blank=True, null=True, upload_to='blogs_banner/')),
                ('author_profile', models.ImageField(blank=True, null=True, upload_to='author_profile/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralBlogsContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_contents', to='admins.generalblogs')),
            ],
        ),
    ]
