# Generated by Django 5.0.3 on 2024-03-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0021_multievents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='single_speaker',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_events', to='admins.speaker'),
        ),
    ]
