# Generated by Django 5.0.4 on 2024-08-21 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0021_generalblogs_generalblogscontents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalblogscontents',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_blog_contents', to='admins.generalblogs'),
        ),
    ]
