# Generated by Django 5.0.3 on 2024-03-21 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0022_alter_event_single_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ImageField(upload_to='')),
                ('date', models.DateField(null=True)),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admins.event')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='admins.speaker')),
            ],
        ),
        migrations.DeleteModel(
            name='MultiEvents',
        ),
    ]
