# Generated by Django 5.0.4 on 2024-08-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0022_alter_generalblogscontents_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalblogs',
            name='author_profile',
            field=models.ImageField(blank=True, null=True, upload_to='general-author_profile/'),
        ),
        migrations.AlterField(
            model_name='generalblogs',
            name='blog_banner',
            field=models.ImageField(blank=True, null=True, upload_to='general-blogs_banner/'),
        ),
        migrations.AlterField(
            model_name='generalblogscontents',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='general-blogs/'),
        ),
    ]
