# Generated by Django 5.0.4 on 2024-08-21 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0023_alter_generalblogs_author_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalblogscontents',
            name='blog',
        ),
        migrations.AddField(
            model_name='generalblogscontents',
            name='general_blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_blog_contents', to='admins.generalblogs'),
        ),
    ]
