# Generated by Django 5.0.3 on 2024-03-22 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0024_eventschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventspeaker',
            name='events',
        ),
        migrations.RemoveField(
            model_name='eventspeaker',
            name='speaker',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='points',
        ),
        migrations.RemoveField(
            model_name='event',
            name='single_speaker',
        ),
        migrations.RemoveField(
            model_name='event',
            name='starting_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='event',
            name='youtube_link',
        ),
        migrations.CreateModel(
            name='SingleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ImageField(upload_to='')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('starting_time', models.TimeField(blank=True, null=True)),
                ('ending_time', models.TimeField(blank=True, null=True)),
                ('topics', models.TextField(blank=True, null=True)),
                ('events', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admins.event')),
                ('single_speaker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_events', to='admins.speaker')),
            ],
        ),
        migrations.DeleteModel(
            name='EventSchedule',
        ),
        migrations.DeleteModel(
            name='EventSpeaker',
        ),
    ]
