# Generated by Django 5.0.3 on 2024-03-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0025_remove_eventspeaker_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleevent',
            name='days',
            field=models.IntegerField(),
        ),
    ]
