# Generated by Django 5.0.4 on 2024-08-21 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0025_alter_generalblogscontents_general_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalblogscontents',
            old_name='general_blog',
            new_name='blog',
        ),
    ]
