# Generated by Django 5.0.3 on 2024-03-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0026_alter_singleevent_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleevent',
            name='days',
        ),
        migrations.AddField(
            model_name='event',
            name='days',
            field=models.IntegerField(null=True),
        ),
    ]
