# Generated by Django 5.0.4 on 2024-08-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0026_rename_general_blog_generalblogscontents_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.TextField(null=True),
        ),
    ]
