# Generated by Django 5.0.3 on 2024-03-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0028_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
    ]
