# Generated by Django 5.0.4 on 2024-08-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0029_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000, null=True, unique=True),
        ),
    ]
