# Generated by Django 5.0.4 on 2024-08-28 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0030_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=1000, null=True)),
                ('date', models.DateField(null=True)),
                ('days', models.IntegerField(null=True)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/')),
                ('slug', models.SlugField(blank=True, max_length=1000, null=True, unique=True)),
                ('speakers', models.ManyToManyField(blank=True, related_name='general_events', to='admins.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralMultiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.TimeField(blank=True, max_length=8, null=True)),
                ('ending_time', models.TimeField(blank=True, max_length=8, null=True)),
                ('topics', models.TextField(blank=True, null=True)),
                ('single_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_multi_events', to='admins.singleevent')),
                ('single_speaker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_selected_events', to='admins.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSingleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('highlights', models.TextField(blank=True, null=True)),
                ('date', models.DateField(null=True)),
                ('day', models.IntegerField(null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_single_events', to='admins.event')),
            ],
            options={
                'unique_together': {('event', 'day')},
            },
        ),
    ]
