# Generated by Django 5.0.3 on 2024-03-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0030_remove_singleevent_events_singleevent_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleevent',
            name='event',
        ),
        migrations.AddField(
            model_name='singleevent',
            name='events',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='admins.event'),
        ),
    ]
