# Generated by Django 5.0.4 on 2024-08-28 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0031_generalevent_generalmultievent_generalsingleevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalmultievent',
            name='single_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_multi_events', to='admins.generalsingleevent'),
        ),
        migrations.AlterField(
            model_name='generalsingleevent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_single_events', to='admins.generalevent'),
        ),
    ]
