# Generated by Django 5.0.4 on 2024-08-31 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0032_alter_generalmultievent_single_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_certificates', to='admins.event')),
            ],
        ),
    ]
