# Generated by Django 5.0.4 on 2024-08-31 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0033_generalcertificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalcertificates',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_certificates', to='admins.generalevent'),
        ),
    ]
