# Generated by Django 5.0.4 on 2024-09-02 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0034_alter_generalcertificates_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('single_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_attachments', to='admins.generalsingleevent')),
            ],
        ),
    ]
