# Generated by Django 5.0.3 on 2024-04-09 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0035_singleevent_highlights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleevent',
            name='ending_time',
        ),
        migrations.RemoveField(
            model_name='singleevent',
            name='single_speaker',
        ),
        migrations.RemoveField(
            model_name='singleevent',
            name='starting_time',
        ),
        migrations.RemoveField(
            model_name='singleevent',
            name='topics',
        ),
        migrations.CreateModel(
            name='MultiEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_time', models.TimeField(blank=True, null=True)),
                ('ending_time', models.TimeField(blank=True, null=True)),
                ('topics', models.TextField(blank=True, null=True)),
                ('single_speaker', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_events', to='admins.speaker')),
                ('sinlge_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multi_events', to='admins.singleevent')),
            ],
        ),
    ]
