# Generated by Django 5.0.4 on 2024-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0036_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='period',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
