# Generated by Django 5.0.3 on 2024-04-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0036_remove_singleevent_ending_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multievent',
            old_name='sinlge_event',
            new_name='single_event',
        ),
    ]
