# Generated by Django 5.0.3 on 2024-04-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0037_rename_sinlge_event_multievent_single_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multievent',
            old_name='single_event',
            new_name='sinlge_event',
        ),
    ]
