# Generated by Django 5.0.3 on 2024-04-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0038_rename_single_event_multievent_sinlge_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multievent',
            old_name='sinlge_event',
            new_name='single_event',
        ),
    ]
