# Generated by Django 5.0.4 on 2024-04-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0039_rename_sinlge_event_multievent_single_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleevent',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='singleevent',
            name='day',
            field=models.IntegerField(null=True),
        ),
    ]
