from django.urls import path
 
from .views import *

urlpatterns = [
    path('login/',AdminLogin.as_view(), name='admin_login'),
    path('forums/', ForumListCreate.as_view(), name='forum-list-create'),
    path('forums/<int:pk>/update/', ForumUpdateView.as_view(), name='forum-update'),
    path('forums/<int:pk>/delete/', ForumDeleteView.as_view(), name='forum-delete'),
    path('speakers/', SpeakerListCreate.as_view(), name='speaker-list-create'),
    path('speakers/<int:pk>/update/', SpeakerUpdateView.as_view(), name='speaker-update'),
    path('speakers/<int:pk>/delete/', SpeakerDeleteView.as_view(), name='speaker-delete'), 
    path('eventcreate/', EventListCreate.as_view() , name='event_create'),
    path('events/', EventListView.as_view(), name='events-list'),     
    # path('events/<int:pk>/update/', EditEventAPIView.as_view(), name='edit_event'),
    path('events/<int:pk>/list/', EventDetailView.as_view(), name='event-detail'),
    path('eventslist/', EventListView.as_view(), name='event-list'),
    path('events/<int:event_id>/single-events/', SingleEventDetailView.as_view(), name='single-events-detail'),
    path('enroll/<int:event_id>/single-events/', SingleDetailView.as_view(), name='single-events-enroll'),
    path('events/<int:event_id>/speakers/', EventSpeakersView.as_view(), name='event-speakers'),
    path('eventslistb/', EventListbannerView.as_view(), name='event-list'),
    path('members/', MemberListCreate.as_view(), name='member-list-create'),
    path('members/<int:pk>/update/', MemberUpdateView.as_view(), name='member-update'),
    path('members/<int:pk>/delete/', MemberDeleteView.as_view(), name='member-delete'),
    path('forummembers/', ForumMemberCreateView.as_view(), name='member-create'),
    path('forummembers/<int:forum_id>/', ForumMemberListView.as_view(), name='forum_members_list'),
    path('forummembers/<int:forum_id>/update/', ForumMemberView.as_view(), name='update_forum_member'),
    path('blogs/', CreateBlog.as_view(), name='blog_admin'),
    path('blogslist/', BlogListView.as_view(), name='blog-list'),
    path('blogs/<int:pk>/delete/', BlogDeleteView.as_view(), name='blogs-delete'),
    path('blogs/<int:pk>/update/', BlogUpdateView.as_view(), name='forum-update'),
    path('certificates/',certificatesCreate.as_view(), name='certificate-list-create'),
    path('certificates/<int:pk>/delete', CertificatesDeleteView.as_view(), name='certificates-delete'),
    path('certificateslist/', CertificatesList.as_view(), name='certificates-list'),
    path('certificates/<int:pk>/', CertificatesDetail.as_view(), name='certificate-detail'),
    path('banner/', BannerListCreate.as_view(), name='banner-list-create'),
    path('banner/<int:pk>/update/', BannerUpdateView.as_view(), name='banner-update'),
    path('banner/<int:pk>/delete/', BannerDeleteView.as_view(), name='banner-delete'),
    path('news/', NewsListCreate.as_view(), name='news-list-create'),
    path('news/<int:pk>/update/', NewsUpdateView.as_view(), name='news-update'),
    path('news/<int:pk>/delete/', NewsDeleteView.as_view(), name='news-delete'),
]     
 